#!/bin/bash

step () {
    echo -e "\e[1;35m==> $1\e[0m"
}

SCRIPT_DIR=`dirname $0`

#-------------------------------------------------------------------------------
step 'Update'
#-------------------------------------------------------------------------------

sudo pacman -Syu

#-------------------------------------------------------------------------------
step 'Plasma'
#-------------------------------------------------------------------------------

sudo pacman -S plasma-meta

#-------------------------------------------------------------------------------
step 'Soft'
#-------------------------------------------------------------------------------

sudo pacman -S dolphin konsole kwrite chromium ffmpegthumbs kdegraphics-thumbnailers kdialog libva-mesa-driver noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-fira-code ttf-liberation ark unrar kmahjongg kpatience nomacs okular qbittorrent kcalc spectacle kwalletmanager kdeconnect sshfs ntfs-3g mpv youtube-dl wget neofetch php php-sqlite xdebug composer unzip code

#-------------------------------------------------------------------------------
step 'Swap'
#-------------------------------------------------------------------------------

sudo dd if=/dev/zero of=/swapfile bs=1M count=1024 status=progress
sudo chmod 600          /swapfile
sudo mkswap             /swapfile
sudo swapon             /swapfile
sudo sh -c 'echo /swapfile none swap defaults 0 0 >> /etc/fstab'

#-------------------------------------------------------------------------------
step 'Data'
#-------------------------------------------------------------------------------

sudo mkdir -p                               /media/data
sudo chown -R qtm:users                     /media/data
sudo sh -c 'echo LABEL=DATA /media/data ext4 defaults,noatime,nofail 0 2 >> /etc/fstab'

#-------------------------------------------------------------------------------
step 'Config'
#-------------------------------------------------------------------------------

mkdir -p ~/.config

cp  -f  $SCRIPT_DIR/bash/.bashrc            ~/
cp  -rf $SCRIPT_DIR/mpv                     ~/.config/

sudo chown -R qtm:users                     $SCRIPT_DIR/apps
sudo chmod -R 777                           $SCRIPT_DIR/apps
sudo cp $SCRIPT_DIR/apps/pacinfo            /usr/bin

#-------------------------------------------------------------------------------
step 'Display manager'
#-------------------------------------------------------------------------------

systemctl enable sddm.service

#-------------------------------------------------------------------------------
step 'Done!'
#-------------------------------------------------------------------------------
